### ISSUE TITLE
Scala question and where do I get JAR for EmbeddedKafkaCluster

### ISSUE THREAD

**Issue by sachabarber** [bbejeck/kafka-streams-in-action#1]
Firstly great book, thanks a million for it. Great

I hope you don't mind but just got a few questions, happy to do this some other way, if you want just let me know.

However if you are ok to help with 2 small questions.

1. You use EmbeddedKafkaCluster, but what JAR would I need to get this in a IntelliJ IDEA SBT project. Got a link to what artifact it is in Maven Central. I could not tell from your Maven file which one it was

2. I can see that there was a whole bunch of stuff brought into 2.0.0 (which I am using) to make working with Serdes easier from Scala. https://github.com/apache/kafka/tree/2.0/streams/streams-scala/src/main/scala/org/apache/kafka/streams/scala

This is based on the https://github.com/lightbend/kafka-streams-scala repo, that has now been folded into official apache/kafka codebase.

My question is, why don't I see these scala types if I am using the 2.0.0 artifact

I raised a question here too : https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/confluent-platform/f_umV-B6Spw

Its just being the author of the ONLY book on this subject, and if I am not mistaken you work for Confluent too right, so I thought if anyone knows it will be you.

I hope you dont mind direct question here, im really struggling to get this working

**Comment by sachabarber** [comment]
One of the confluent guys gave me answer to the scala query, so I'll close this issue. Unless you feel like letting me know what artifact I need for the EmbeddedKafkaCluster

**Comment by bbejeck** [comment]
Hi, @sachabarber 
I believe the `EmbeddedKafkaCluster` is now (version `2.0`) in the `streams-test-utils` module.  
At the time when I wrote the book, I believe it is part of the `streams-test` dependency.  Let me know if you need anything else.

**Comment by sachabarber** [comment]
Awesome thanks. As I say great book. If I find some time, I intend on redoing most of your book examples in Scala. If I get around to that I will let you know, might be good to have a link to that here. But its also XMAS soon, so may not happen quickly

Again thanks

**Comment by sachabarber** [comment]
Yeah scala is a weird one, as its way less verbose than Java. but the implicits make it crazy at times, and thats not even including all the functional stuff like Cats/Lenses/Shapeless/monad trandformers etc etc

**Comment by mulho** [comment]
I'm sorry, but I still can't find `EmbeddedKafkaCluster` in `streams-test-utils`. I have added these dependencies to my project, but this class doesn't seems to be in any of those:
```
		<dependency>
		    <groupId>org.apache.kafka</groupId>
		    <artifactId>kafka-streams-test-utils</artifactId>
		    <version>2.0.1</version>
		    <scope>test</scope>
		</dependency>
		<dependency>
		    <groupId>org.apache.kafka</groupId>
		    <artifactId>kafka-streams-test-utils</artifactId>
		    <version>2.0.1</version>
		    <scope>test</scope>
		    <classifier>test</classifier>
		</dependency>
```
Should I be looking at a different dependency?
Thanks

**Comment by mulho** [comment]
Answering my own question, here is where I found it:
```
		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-streams</artifactId>
			<version>2.0.1</version>
			<scope>test</scope>
			<classifier>test</classifier>
		</dependency>
```
